{%- macro getNameOrArgs(p) -%}    
    {%- if p.prefix and p.prefix_long -%}'{{p.prefix}}', '{{p.prefix_long}}', dest=
    {%- elif p.arg -%}'{{p.prefix}}', dest=
    {%- elif p.arg_long -%}'{{p.prefix_long}}', dest=
    {%- endif -%}'{{p.name}}'
{%- endmacro -%}

{%- macro getType(type) -%}
    , type=
    {%- if type == 'integer' -%}int
    {%- elif type in ['None', 'boolean'] -%}bool
    {%- elif type in ['string','select'] -%}str
    {%- elif type == 'float' -%}float
    {%- elif type in ['input', 'stdin'] -%}argparse.FileType('r')
    {%- elif type in ['output', 'stdout', 'stderr'] -%}argparse.FileType('w')
    {%- endif -%}
{%- endmacro -%}

{%- macro getOptionalSettings(p) -%}
    {#- default values -#}
    {%- if p.arg_type in ['stdin', 'stdout', 'stderr'] -%}, default=sys.{{p.type}}, nargs='?'
    {%- elif p.arg_type == 'None' -%}, nargs='?', default=False, const=True
    {%- elif p.value -%}, default=
        {%- if p.arg_type == 'string' -%}'{{p.value}}'
        {%- elif p.arg_type == 'select' -%}"{{p.value[0]}}", choices={{p.value}}
        {%- else -%}{{p.value}}
        {%- endif -%}
    {%- endif -%}
    
    {#- required -#}
    {%- if p.required == 'True' and (p.prefix or p.prefix_long) -%}
        , required=True
    {%- endif -%}
    
    {#- repeatable -#}
    {%- if p.repeatable == 'True' -%}
        , nargs='+'
    {%- endif -%}
    
    {#- help -#}
    {%- if p.label or p.description -%}
        , {{("\nhelp='" + (p.label or p.description))|indent(12, true)}}'
    {%- endif -%}
{%- endmacro -%}
#!/usr/bin/python

"""
{{data.name}}:
{{data.description}}

Handle argument parsing for main.py.
Requires Python version >= 2.7.
If you have Python 2.6, you can manually add argparse as a standalone Module.

@requires: sys
@requires" argparse
"""

import sys
import argparse

def parse() :
    """
    Parse the command line, do all necessary checks and return the arguments
    as a dictionary.
    
    Auto generated by:
        {{ meta.version }}
        {{ meta.time }}

    Based on:
        {{ meta.label }}
        {{ meta.last_modified }}

    @returns: An object with the parsed arguments.
    @rtype: argparse.Namspace
    """
    
    parser = argparse.ArgumentParser(
            prog='{{data.binary}}',
            formatter_class=argparse.RawDescriptionHelpFormatter,
            description='{{data.description}}',
            epilog="""{{data.help}}""")
    
    {% for arg in data.arguments -%}
        parser.add_argument({{getNameOrArgs(arg)}}{{getType(arg.arg_type)}}{{getOptionalSettings(arg)}})
    {% endfor %}
    
    arguments = parser.parse_args()
    
    return arguments
#parse

################################################################################
# usage example
#
#def main():
#   arguments = parse()
#   
#   # Your program logic here. 
#   # Use arguments.<arg_name> to access an argument
# 
##def main
#
#if __name__ == "__main__": 
#   main()
################################################################################